name: Automation Script for Python

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-18.04
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Linting
        run: |
          /bin/sh .github/workflows/python.linter.sh
      - name: Testing
        run: |
          /bin/sh .github/workflows/python.tester.sh
      - name: Reporting
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flag: python
