name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-18.04
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing
        uses: actions/setup-python@v1
        with:
          python-version: '3.5'
      - name: Testing
        run: |
          cd algorithm-design/python
          python3 hackerrank/suite.py
